---
repos:
  - repo: https://github.com/norwoodj/helm-docs
    rev:  "v1.14.2"
    hooks:
      - id: helm-docs-built
        args:
          - --chart-search-root=./helm-chart
          - --template-files=README.md.gotmpl
          - --sort-values-order=file
