{
 "title": "Mezod Validator",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "chain_id",
    "query": {
     "query": "label_values(cometbft_consensus_height,chain_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Synchronization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sync status",
     "type": "timeseries",
     "description": "0=synced, 1=syncing",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "cometbft_blocksync_syncing{chain_id=\"$chain_id\", job=\"mezod-cometbft\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Synced blocks",
     "type": "timeseries",
     "description": "Active only during synchronization",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "cometbft_blocksync_latest_block_height{chain_id=\"$chain_id\", job=\"mezod-cometbft\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Consensus",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current numbers",
     "type": "stat",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cometbft_consensus_height{chain_id=\"$chain_id\", job=\"mezod-cometbft\"}",
       "legendFormat": "Height"
      },
      {
       "expr": "cometbft_consensus_latest_block_height{chain_id=\"$chain_id\", job=\"mezod-cometbft\"}",
       "legendFormat": "Latest block"
      },
      {
       "expr": "cometbft_consensus_validator_last_signed_height{chain_id=\"$chain_id\", job=\"mezod-cometbft\"}",
       "legendFormat": "Signed"
      }
     ]
    },
    {
     "title": "Consensus height",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 19, "x": 5, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "cometbft_consensus_height{chain_id=\"$chain_id\", job=\"mezod-cometbft\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "cometbft_consensus_latest_block_height{chain_id=\"$chain_id\", job=\"mezod-cometbft\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "cometbft_consensus_validator_last_signed_height{chain_id=\"$chain_id\", job=\"mezod-cometbft\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Average block processing time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(cometbft_state_block_processing_time_sum{chain_id=\"$chain_id\", job=\"mezod-cometbft\"}[5m]) / rate(cometbft_state_block_processing_time_count{chain_id=\"$chain_id\", job=\"mezod-cometbft\"}[5m])",
       "legendFormat": "Block processing"
      }
     ]
    },
    {
     "title": "Block interval",
     "type": "timeseries",
     "description": "Average is calculated for all blocks. 95th is calculated for the 95% of the highest intervals.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(cometbft_consensus_block_interval_seconds_sum{chain_id=\"$chain_id\", job=\"mezod-cometbft\"}[5m]) / rate(cometbft_consensus_block_interval_seconds_count{chain_id=\"$chain_id\", job=\"mezod-cometbft\"}[5m])",
       "legendFormat": "Average"
      },
      {
       "expr": "histogram_quantile(0.95, rate(cometbft_consensus_block_interval_seconds_bucket{chain_id=\"$chain_id\", job=\"mezod-cometbft\"}[5m]))",
       "legendFormat": "95th percentile"
      }
     ]
    },
    {
     "title": "Block size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "cometbft_consensus_block_size_bytes{chain_id=\"$chain_id\", job=\"mezod-cometbft\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Chain size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "cometbft_consensus_chain_size_bytes{chain_id=\"$chain_id\", job=\"mezod-cometbft\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Rate of duplicated block parts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "rate(cometbft_consensus_duplicate_block_part{chain_id=\"$chain_id\", job=\"mezod-cometbft\"}[5m])",
       "legendFormat": "cometbft_consensus_duplicate_block_part"
      }
     ]
    },
    {
     "title": "Rate of duplicated votes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "expr": "rate(cometbft_consensus_duplicate_vote{chain_id=\"$chain_id\", job=\"mezod-cometbft\"}[5m])",
       "legendFormat": "cometbft_consensus_duplicate_vote"
      }
     ]
    },
    {
     "title": "Full prevote delay",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "cometbft_consensus_full_prevote_delay{chain_id=\"$chain_id\", job=\"mezod-cometbft\"}",
       "legendFormat": "{{proposer_address}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average number of TXs in block",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg(rate(cometbft_consensus_num_txs{chain_id=\"$chain_id\", job=\"mezod-cometbft\"}[5m]))",
       "legendFormat": "Number"
      }
     ]
    },
    {
     "title": "Total number of TXs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "cometbft_consensus_total_txs{chain_id=\"$chain_id\", job=\"mezod-cometbft\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Validator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Voting Power",
     "type": "stat",
     "gridPos": { "h": 8, "w": 3, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cometbft_consensus_validator_power{chain_id=\"$chain_id\", job=\"mezod-cometbft\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Validators",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 3, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "cometbft_consensus_validators{chain_id=\"$chain_id\", job=\"mezod-cometbft\"}",
       "legendFormat": "count"
      },
      {
       "expr": "cometbft_consensus_validators_power{chain_id=\"$chain_id\", job=\"mezod-cometbft\"}",
       "legendFormat": "power"
      }
     ]
    }
   ]
  },
  {
   "title": "RPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPC all calls duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rpc_duration_all_count{job=\"mezod-evm\"})",
       "legendFormat": "All count"
      }
     ]
    },
    {
     "title": "RPC requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rpc_requests{job=\"mezod-evm\"})",
       "legendFormat": "All requests"
      },
      {
       "expr": "sum(rpc_success{job=\"mezod-evm\"})",
       "legendFormat": "Successful requests"
      },
      {
       "expr": "sum(rpc_failure{job=\"mezod-evm\"})",
       "legendFormat": "Failed requests"
      }
     ]
    }
   ]
  },
  {
   "title": "P2P",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Peers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "cometbft_p2p_peers{chain_id=\"$chain_id\", job=\"mezod-cometbft\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Mempool active outbound connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "cometbft_mempool_active_outbound_connections{chain_id=\"$chain_id\", job=\"mezod-cometbft\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Receive/sent bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(cometbft_p2p_message_receive_bytes_total{chain_id=\"$chain_id\", job=\"mezod-cometbft\"})",
       "legendFormat": "Received"
      },
      {
       "expr": "sum(cometbft_p2p_message_send_bytes_total{chain_id=\"$chain_id\", job=\"mezod-cometbft\"})",
       "legendFormat": "Sent"
      }
     ]
    }
   ]
  },
  {
   "title": "ABCI",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate of requests for each ABCI method",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by(method) (rate(cometbft_abci_connection_method_timing_seconds_count{chain_id=\"$chain_id\", job=\"mezod-cometbft\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average latency for each ABCI method",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(cometbft_abci_connection_method_timing_seconds_sum{chain_id=\"$chain_id\", job=\"mezod-cometbft\"}[5m]) / rate(cometbft_abci_connection_method_timing_seconds_count{chain_id=\"$chain_id\", job=\"mezod-cometbft\"}[5m])",
       "legendFormat": "{{method}}"
      }
     ]
    }
   ]
  }
 ]
}