{
 "title": "Overview",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "UP jobs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "up", "legendFormat": "{{job}}" }
   ]
  },
  { "title": "Alertmanager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Sent notifications per integration",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "alertmanager_notifications_total{job=\"alertmanager\"}",
     "legendFormat": "{{integration}}"
    }
   ]
  },
  {
   "title": "Sent notifications per integration (failures)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum (alertmanager_notifications_failed_total{job=\"alertmanager\"}) by (integration)",
     "legendFormat": "{{integration}}"
    }
   ]
  },
  {
   "title": "Alerts per state",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "alertmanager_alerts{job=\"alertmanager\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Silence per state",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "alertmanager_silences{job=\"alertmanager\"}",
     "legendFormat": "{{state}}"
    }
   ]
  }
 ]
}