{{- if or .Values.customConfigs.enabled 
  (or 
    (eq .Values.nodeType "seed")
    (eq .Values.nodeType "rpc")
  ) 
}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "custom-configs-{{ include "this.name" . }}"
  labels:
    node_type: {{ .Values.nodeType }}
    {{- include "this.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  app.toml.txt: |
  {{- if .Values.customConfigs.appTomlTxt }}
    {{- .Values.customConfigs.appTomlTxt | nindent 4 }}
  {{- end }}
  {{- if eq .Values.nodeType "rpc-archive" }}
    pruning=nothing
  {{- end }}
  {{- if .Values.customConfigs.clientTomlTxt }}
  client.toml.txt: |
    {{- .Values.customConfigs.clientTomlTxt | nindent 4 }}
  {{- end }}
  config.toml.txt: |
  {{- if .Values.customConfigs.configTomlTxt }}
    {{- .Values.customConfigs.configTomlTxt | nindent 4 }}
  {{- end }}
  {{- if eq .Values.nodeType "seed" }}
    p2p.seed_mode=true
  {{- end }}
{{- end }}
