---
{{- if .Values.customConfigs.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "custom-configs-{{ include "this.name" . }}"
  labels:
    {{- include "this.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  {{- if .Values.customConfigs.appTomlTxt }}
  app.toml.txt: |
    {{- .Values.customConfigs.appTomlTxt | nindent 4 }}
  {{- end }}
  {{- if .Values.customConfigs.clientTomlTxt }}
  client.toml.txt: |
    {{- .Values.customConfigs.clientTomlTxt | nindent 4 }}
  {{- end }}
  {{- if .Values.customConfigs.configTomlTxt }}
  config.toml.txt: |
    {{- .Values.customConfigs.configTomlTxt | nindent 4 }}
  {{- end }}
{{- end }}
