---
{{- if .Values.customConfigs.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "custom-configs-{{ include "this.name" . }}"
  labels:
    {{- include "this.labels" . | nindent 4 }}
data:
  app.toml.txt: |
    {{- .Values.customConfigs.appTomlTxt | nindent 4 }}
  client.toml.txt: |
    {{- .Values.customConfigs.clientTomlTxt | nindent 4 }}
  config.yaml.txt: |
    {{- .Values.customConfigs.configTomlTxt | nindent 4 }}
{{- end }}
