---
{{- if .Values.service.public.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "public-{{ include "this.name" . }}"
  labels:
    {{- include "this.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.service.public.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    mezo.org/node_type: {{ .Values.nodeType | quote }}
spec:
  type: {{ .Values.service.public.type | quote }}
  {{- if .Values.service.public.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.public.loadBalancerIP | quote }}
  {{- end }}
  allocateLoadBalancerNodePorts: {{ .Values.service.public.allocateLoadBalancerNodePorts }}
  selector:
    {{- include "this.selectorLabels" . | nindent 4 }}
  ports:
    {{- range $key, $value := .Values.service.public.ports }}
    - name: {{ $key }}
      port: {{ int $value }}
      targetPort: {{ $key }}
    {{- end }}
{{- end }}
