apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "this.name" . | quote }}
  labels:
    {{- include "this.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: false
