---
{{- if .Values.service.private.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "private-{{ include "this.name" . }}"
  labels:
    {{- include "this.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  selector:
    {{- include "this.selectorLabels" . | nindent 4 }}
  ports:

  {{- if hasKey .Values.service.public.ports "evm-metrics" }}
    - name: evm-metrics
      port: {{ index .Values.service.public.ports "evm-metrics" }}
      targetPort: evm-metrics
  {{- end }}

  {{- if hasKey .Values.service.public.ports "comet-metrics" }}
    - name: comet-metrics
      port: {{ index .Values.service.public.ports "comet-metrics" }}
      targetPort: comet-metrics
  {{- end }}

{{- end }}
