apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "this.name" . | quote }}
  labels:
    {{- include "this.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: 1
  serviceName: {{ include "this.name" . | quote }}
  selector:
    matchLabels:
      {{- include "this.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "this.selectorLabels" . | nindent 8 }}
        {{- with .Values.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- if .Values.customConfigs.enabled }}
      annotations:
        # This annotation ensures the StatefulSet is updated when the ConfigMap changes
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum | quote }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "this.name" . | quote }}
      automountServiceAccountToken: false
      securityContext:
        runAsUser: {{ .Values.securityContext.userId }}
        runAsGroup: {{ .Values.securityContext.groupId }}
        fsGroup: {{ .Values.securityContext.groupId }}
        fsGroupChangePolicy: "OnRootMismatch"
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName | quote }}
      {{- end }}
      volumes:
        - name: dummy-data
          emptyDir: {}
        {{- if .Values.customConfigs.enabled }}
        - name: custom-configs
          configMap:
            name: "custom-configs-{{ include "this.name" . }}"
        {{- end }}
      containers:
        #
        # The main container with the mezod application
        #
        - name: mezod
          image: "{{ .Values.image }}:{{ .Values.tag }}"
          imagePullPolicy: IfNotPresent
          {{- if .Values.maintenanceMode }}
          args:
            - /bin/sh
            - -c
            - 'trap "exit" TERM; while true; do sleep 1; done'
          {{- else }}
          args:
            - mezod
            - start
            - --home={{ .Values.env.MEZOD_HOME }}
            - --metrics
            - --log_format={{ .Values.env.MEZOD_LOG_FORMAT }}
            - --log_level={{ .Values.env.MEZOD_LOG_LEVEL }}
            - --log_no_color
          {{- end }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value }}
            {{- end }}
            - name: KEYRING_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret | quote }}
                  key: KEYRING_NAME
            - name: KEYRING_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret | quote }}
                  key: KEYRING_PASSWORD
            - name: KEYRING_MNEMONIC
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret | quote }}
                  key: KEYRING_MNEMONIC
          ports:
            {{- range $key, $value := .Values.service.public.ports }}
            - name: {{ $key }}
              containerPort: {{ int $value }}
              protocol: TCP
            {{- end }}
            {{- range $key, $value := .Values.service.private.ports }}
            - name: {{ $key }}
              containerPort: {{ int $value }}
              protocol: TCP
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            capabilities:
              drop:
                - ALL
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: data
              mountPath: {{ .Values.env.MEZOD_HOME | quote }}
            {{- if .Values.customConfigs.enabled }}
            - name: custom-configs
              mountPath: /config/
            {{- end }}
        #
        # The sidecar container for ethereum
        #
        - name: ethereum-sidecar
          image: "{{ .Values.image }}:{{ .Values.tag }}"
          imagePullPolicy: IfNotPresent
          command:
            - mezod
            - ethereum-sidecar
            - --home=/tmp/dummy-data
            - --log_format=json
            - --ethereum-sidecar.server.ethereum-node-address=$(ETHEREUM_ENDPOINT)
          env:
            - name: ETHEREUM_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret | quote }}
                  key: ETHEREUM_ENDPOINT
          ports:
            - name: client
              containerPort: 7500
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
          securityContext:
            capabilities:
              drop:
                - ALL
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: dummy-data
              mountPath: /tmp/dummy-data
        #
        # The sidecar container for Skip connect application
        #
        - name: connect-sidecar
          image: "{{ .Values.connectSidecar.image }}:{{ .Values.connectSidecar.tag }}"
          imagePullPolicy: IfNotPresent
          command:
            - connect
            - --disable-telemetry
            - --log-disable-file-rotation
            - --port={{ .Values.connectSidecar.ports.http }}
            - --market-map-endpoint=localhost:{{ .Values.service.public.ports.grpc }}
          ports:
            - name: http
              containerPort: {{ .Values.connectSidecar.ports.http }}
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
          securityContext:
            capabilities:
              drop:
                - ALL
            allowPrivilegeEscalation: false
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: {{ .Values.storage.className | quote }}
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: {{ .Values.storage.size | quote }}
        {{- if .Values.storage.useDataSource.enabled }}
        dataSource:
          apiGroup: {{ .Values.storage.useDataSource.apiGroup | quote }}
          kind: {{ .Values.storage.useDataSource.kind | quote }}
          name: {{ .Values.storage.useDataSource.name | quote }}
        {{- end }}
